# Options to enable in debug builds

# Thread info for OpenOCD RTOS awareness
CONFIG_DEBUG_THREAD_INFO=y

# CONFIG_LOG_DEFAULT_LEVEL=4

# Periodically print thread stack usage
# CONFIG_THREAD_ANALYZER=y
# CONFIG_THREAD_ANALYZER_USE_LOG=y
# CONFIG_THREAD_ANALYZER_AUTO=y
# CONFIG_THREAD_ANALYZER_AUTO_INTERVAL=5