### General
# Heap, used by TF-PSA-Crypto
CONFIG_COMMON_LIBC_MALLOC_ARENA_SIZE=512
# BLE pairing work uses 1056 bytes
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=1280

### Thread priorities
CONFIG_MAIN_THREAD_PRIORITY=0
# Prevent crypto tasks from blocking logging
CONFIG_LOG_PROCESS_THREAD_CUSTOM_PRIORITY=y
CONFIG_LOG_PROCESS_THREAD_PRIORITY=13
# Run slow crypto tasks in background
CONFIG_BT_LONG_WQ_PRIO=14

### BLE config
CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DEVICE_NAME="Water Level"
CONFIG_BT_DEVICE_APPEARANCE=5184
CONFIG_BT_MAX_CONN=2
CONFIG_BT_MAX_PAIRED=2

### BLE security
CONFIG_BT_SMP=y
CONFIG_BT_SMP_SC_ONLY=y
# Workqueue for long running crypto tasks
CONFIG_BT_LONG_WQ=y
# BLE pairing with a fixed passkey can be easily brute forced [0]. This leaves
# it with the same security as always enabled "just works" pairing, but with the
# advantage that random (non-technical) passersby can't connect. I could display
# a random passkey over UART, but this would require disassembling the sensor to
# pair with it. In this low stakes application, I care more about reliability
# (and being able to fix problems remotely) than security.
# [0] https://insinuator.net/2021/10/change-your-ble-passkey-like-you-change-your-underwear/
CONFIG_BT_FIXED_PASSKEY=y
CONFIG_BT_DEFAULT_PASSKEY=207943
CONFIG_BT_SETTINGS=y

CONFIG_FLASH=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_FLASH_MAP=y
CONFIG_NVS=y
CONFIG_SETTINGS=y
CONFIG_SETTINGS_NVS=y

# Logging
CONFIG_LOG=y
CONFIG_LOG_MODE_DEFERRED=y

### Water level sensor
CONFIG_GPIO=y
CONFIG_PM_DEVICE=y
CONFIG_SENSOR=y
CONFIG_JSN_SR04T=y

### Temperature sensor
CONFIG_TEMP_NRF5=y

### Battery voltage
CONFIG_ADC=y
CONFIG_NRFX_ADC_SUPPLY=y

### Crash handling
CONFIG_REBOOT=y
