### Common
# Heap, used by TF-PSA-Crypto
CONFIG_COMMON_LIBC_MALLOC_ARENA_SIZE=512

### Thread priorities
CONFIG_MAIN_THREAD_PRIORITY=0
# Prevent crypto tasks from blocking logging
CONFIG_LOG_PROCESS_THREAD_CUSTOM_PRIORITY=y
CONFIG_LOG_PROCESS_THREAD_PRIORITY=13
# Run slow crypto tasks in background
CONFIG_BT_LONG_WQ_PRIO=14

### BLE config
CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DEVICE_NAME="Water Level"
CONFIG_BT_DEVICE_APPEARANCE=5184
CONFIG_BT_MAX_CONN=2
CONFIG_BT_MAX_PAIRED=2

### BLE security
CONFIG_BT_SMP=y
CONFIG_BT_SMP_SC_ONLY=y
# Workqueue for long running crypto tasks
CONFIG_BT_LONG_WQ=y
CONFIG_BT_FIXED_PASSKEY=y
CONFIG_BT_DEFAULT_PASSKEY=207943
CONFIG_BT_SETTINGS=y

CONFIG_FLASH=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_FLASH_MAP=y
CONFIG_NVS=y
CONFIG_SETTINGS=y
CONFIG_SETTINGS_NVS=y

# Logging
CONFIG_LOG=y
CONFIG_LOG_MODE_DEFERRED=y

### Water level sensor
CONFIG_GPIO=y
CONFIG_PM_DEVICE=y
CONFIG_SENSOR=y
CONFIG_JSN_SR04T=y

### Temperature sensor
CONFIG_TEMP_NRF5=y

### Battery voltage
CONFIG_ADC=y
CONFIG_NRFX_ADC_SUPPLY=y

### Crash handling
CONFIG_REBOOT=y

### Code size optimization
CONFIG_SPI=n
