manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: lopsided98
      url-base: https://github.com/lopsided98
  projects:
    - name: zephyr
      remote: lopsided98
      revision: 487d489b6f0abbbab754a559627222def971b493
      import:
        name-allowlist:
          - cmsis_6
          - hal_nordic
          - mbedtls
          - tf-psa-crypto
    - name: west-nix
      remote: lopsided98
      revision: 3f31c82804e217842dc40e21ab8f95a037dfc8f7
      import: true
      path: tools/west-nix
  self:
    path: firmware
