[package]
name = "water_level_monitor"
version = "0.1.0"
authors = ["Ben Wolsieffer <benwolsieffer@gmail.com>"]
edition = "2018"

[dependencies]
dbus = "0.6"
reqwest = "0"
url = "1"
url_serde = "0"
byteorder = "1"
clap = "2"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
itertools = "0"
failure = "0"
log = "0"
env_logger = "0"
